#!/bin/bash
date=$(date --date="7 days ago" +"%Y-%m-%d")
dirs=$(ls ~ | grep "Backup")
stringarray=($dirs)
arrLen=${#stringarray[@]}
flag=0;
dir=""
for (( i=0; i<$arrLen; i++ ))
do
currDir=${stringarray[$i]}
dirDate=${currDir:7}
if [[ "$dirDate">"$date" ]]
then
let flag=$flag\+1
dir=$currDir
break
fi
done
if [[ "$flag" -eq 0 ]]
then
dir="Backup-"$(date '+%Y-%m-%d')
fi
[[ -d ~/source ]] ||
{
echo "The course directory doesn't exist." 1>&2
exit -1
}
report="backup-report"
files=$(ls ~/source)
stringarray=($files)
arrLen=${#stringarray[@]}
[[ -f $report ]] || touch ~/$report
if [[ "$flag" -eq 0 ]]
then
mkdir ~/$dir
echo -ne $dir $(date '+%Y-%m-%d') $arrLen" 0 ">> ~/$report 
for (( i=0; i<$arrLen; i++ ))
do
echo -ne ${stringarray[$i]}" " >> ~/$report
cp ~/source/${stringarray[$i]} ~/$dir/${stringarray[$i]}
done
echo " " >> ~/$report
else
newFiles=()
oldFiles=()
for (( i=0; i<$arrLen; i++ ))
do
if [[ ! -f ~/$dir/${stringarray[$i]} ]]
then
cp ~/source/${stringarray[$i]} ~/$dir/${stringarray[$i]}
newFiles+=(${stringarray[$i]})
else
if [[ ! $(stat -c"%s" ~/source/${stringarray[$i]}) -eq $(stat -c"%s" ~/$dir/${stringarray[$i]}) ]]
then
mv ~/$dir/${stringarray[$i]} ~/$dir/${stringarray[$i]}.$(date '+%Y-%m-%d')
cp ~/source/${stringarray[$i]} ~/$dir/${stringarray[$i]}
oldFiles+=(${stringarray[$i]})
fi
fi
done
echo -ne $dir $(date '+%Y-%m-%d') ${#newFiles[@]} ${#oldFiles[@]}" " >> ~/$report
for i in "${newFiles[@]}"
do
echo -ne $i" " >> ~/$report
done
for i in "${oldFiles[@]}"
do
echo -ne $i" "$i.$(date '+%Y-%m-%d')" " >> ~/$report
done
echo " " >> ~/$report
fi


