#!/bin/bash
date=$(date --date="7 days ago" +"%Y-%m-%d")
dirs=$(ls ~ | grep "Backup")
stringarray=($dirs)
arrLen=${#stringarray[@]}
flag=0;
dir=""
for (( i=0; i<$arrLen; i++ ))
do
currDir=${stringarray[$i]}
dirDate=${currDir:7}
if [[ "$dirDate">"$date" ]]
then
let flag=$flag\+1
dir=$currDir
break
fi
done
if [[ "$flag" -eq 0 ]]
then
dir="Backup-"$(date '+%Y-%m-%d')
fi
[[ -d ~/source ]] ||
{
echo "The course directory doesn't exist." 1>&2
exit -1
}
report="backup-report"
files=$(ls ~/source)
stringarray=($files)
arrLen=${#stringarray[@]}
[[ -f $report ]] || touch ~/$report
if [[ "$flag" -eq 0 ]]
then
mkdir ~/$dir
echo -ne $dir $(date '+%Y-%m-%d') $arrLen" ">> ~/$report 
for (( i=0; i<$arrLen; i++ ))
do
echo -ne ${stringarray[$i]}" " >> ~/$report
ln ~/source/${stringarray[$i]} ~/$dir/${stringarray[$i]}
done
echo " " >> ~/$report
fi

