#!/bin/bash
[[ -d ~/.trash ]] ||
{
echo "The trash directory seems to be deleted." 1>&2
exit -1
}
[[ -f ~/.trash.log ]] ||
{
echo "The trash.log file seems to be deleted." 1>&2
exit -1
}
search=$(cat ~/.trash.log | grep $1)
stringarray=($search)
arrLen=${#stringarray[@]}
path=""
link=""
for (( i=0; i<$arrLen; i++ ))
do
if [[ $i\%2 -eq 0 ]]
then 
echo ${stringarray[$i]} "- is that the file you want to revive? [y/n]"
read answer
if [[ "$answer" == "y" ]]
then
path="${stringarray[$i]}"
let i=$i\+1
link="${stringarray[$i]}"
break
fi
fi
done
if [[ "$path" == "" ]]
then 
echo "You've seem to have chosen nothing..." 1>&2
exit -1
fi
dir=$(dirname $path)
dir+="/"
file=$(basename $path)
echo $dir $file
[[ -d dir ]] ||
{
echo "The directory you want to revive your file in doesn't exist. The file will be revived in the home directory."
dir="~/"
}
while [[ -f $dir$file ]]
do
echo "The file with that name $file already exists. Please renme the file:"
read file
done
ln ~/.trash/$link $dir$file
rm ~/.trash/$link
