#!/bin/bash
search=$(cat ~/.trash.log | grep $1)
stringarray=($search)
arrLen=${#stringarray[@]}
path=""
link=""
for (( i=0; i<$arrLen; i++ ))
do
if [[ $i\%2 -eq 0 ]]
then
echo ${stringarray[$i]} "- is that the file you want to revive? [y/n]"
read answer 
if [[ "$answer" == "y" ]]
then
path=${stringarray[$i]}
let i=$i\+1
link=${stringarray[$i]}
break
fi
fi
done
if [[ "$path" == "" ]]
then
echo "You've seem to have chosen nothing..." 1>&2
exit -1
fi
echo $path $link
